<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'User ID' => '用户ID',
    'User type' => '用户类型',
    'Username' => '用户名',
    'Personal name' => '姓名',
    'Identity card' => '身份证',
    'Employe ID' => '员工号',
    'Department ID' => '部门号',
    'Department name' => '部门名称',
    'Mobile' => '手机号',
    'Email' => '邮箱帐号',
    'Password' => '密码',    
    'Created time' => '创建时间',
    'Created by' => '创建者',
    'Last updated time' => '更新时间',
    'Last updated by' => '更新者',
    'User list' => '用户列表',
    '+Add new user' => '+添加新用户',
    'Action' => '操作',
    'Change' => '修改',
    'Save' => '保存',
    'Change user informations' =>'修改用户信息',
    'Reset password' => '重置密码',
    
    'Project ID' => '项目号',
    'State' => '状态',
    'Project name' => '项目名称',
    'Start time' => '启动时间',
    'Target time' => '预计完成时间',
    'Finish time' => '完成时间',
    'Project description' => '项目描述',
    'Normal' => '正常',
    'Finished' => '已完成',
    'Closed' => '关闭',
    'Add new project' => '添加新项目',
    'Project management' =>'项目管理',
    '+Add new project' => '+添加新项目',
    'Project list' => '项目列表',
    
    'Welcome to ' => '欢迎使用',
    'Geely Auto (Shanghai) manhour system' => '吉利汽车（上海）工时管理系统',
    'Geely Auto (Shanghai) ' => '吉利汽车（上海）',
    'Home' => '主页',
    'Man hour record' => '工时记录',
    'User management' => '用户管理',
    'Login' => '登录',
    'Logout' => '登出',
    'Remember me' => '记住我',
    
    'Delete selected projects' => '删除所选项目',
    'Please select at least one row to delete!' => '您还没有选择要删除的行！',
    'Please confirm to delete the selected rows?' => '请确认您要删除这些行数据？',
    

    
    //'{attribute} must be no greater than {max}.' => '{attribute}的值必须不大于{max}。',
    //'{delta, plural, =1{an hour} other{# hours}} ago' => '{delta}小时前',
];
